name: 'setup-yq4'
description: 'Installs the mythical YQ tool'
inputs:
  yq-version:
    description: 'Which version of YQ to install'
    required: false
    default: '4.34.2'
  yq-url:
    description: 'The url to download YQ from'
    required: false
    default: 'https://github.com/mikefarah/yq/releases/download/{version}/yq_{platform}_{arch}'
runs:
  using: 'node16'
  main: 'dist/index.js'
icon: copy
color: purple
